# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
  - label: Features
    link: /features
    submenu:
      - label: For developers
        link: /features-developers
      - label: For designers
        link: /features-designers
      - label: For content creators
        link: /features-content-editors
  - label: Documentation
    link: https://docs.boltcms.io
    target: _blank
  - label: Resources
    submenu:
      - label: Community
        link: /community
      - label: Contribute
        link: /contribute
      - label: Extensions
        link: /extensions
      - label: Showcases
        link: /showcases
      - label: Services and Support
        link: /services-and-support
  - label: No costs
    link: /no-costs
  - label: News
    link: /news
  - label: Try it now!
    link: https://docs.boltcms.io/installation/installation
    class: site-header__end

footer:
#  - label: About Bolt
#    submenu:
#      - label: News
#        link: /news
#      - label: Download latest version
#        link: https://github.com/bolt/core/releases/latest
  - label: Features
    submenu:
      - label: For everyone
        link: /features
      - label: For developers
        link: /features-developers
      - label: For designers
        link: /features-designers
      - label: For content editors
        link: /features-content-editors
  - label: Resources
    submenu:
      - label: Community
        link: /community
      - label: Contribute
        link: /contribute
      - label: Extensions
        link: /extensions
      - label: Services and Support
        link: /services-and-support
  - label: Learn more
    submenu:
      - label: Documentation
        link: https://docs.boltcms.io
      - label: Best practice tips
        link: https://bolt.tips
      - label: Release Roadmap
        link: https://roadmap.boltcms.io
  - label: Explore more
    submenu:
      - label: Showcases
        link: /showcases
      - label: No costs
        link: /no-costs
      - label: News
        link: /news
      - label: Try it!
        link: https://docs.boltcms.io/installation/installation
#  - label: Bolt 3 site
#    link: https://bolt.cm
#    class: bolt-site
#    title: Visit the excellent Bolt website!

